name: CI-CD-Pipeline-to-AWS
env:
 EB_PACKAGES_S3_BUCKET_NAME : "add.github.files"
 EB_APPLICATION_NAME        : "MyWebsite"
 EB_ENVIRONMENT_NAME        : "MyWebsite-env"
 DEPLOY_PACKAGE_NAME        : "website_${{ github.sha }}.zip"
 AWS_REGION_NAME            : "eu-central-1"
 
on:
 push:
  branches: 
   - main

jobs:
 my_ci_part: 
  runs-on: ubuntu-latest 

  steps:
   - name: Git clone our repository
     uses: actions/checkout@v1
   - name: Create ZIP DEPLOYMENT package
     run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
   - name: Configure my AWS Credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
      aws-access-key-id     : ${{ secrets.MY_ACCESS_KEY }}
      aws-secret-access-key : ${{ secrets.MY_SECRET_KEY }}
      aws-region            : ${{ env.AWS_REGION_NAME }}
   - name: Copy Deployment packges to S3 bucket
     run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGES_S3_BUCKET_NAME }}/
   - name: Print happy message
     run : echo "Ci Pipeline part Finished succesfully"
   
   
  
